### ISSUE TITLE
Fails at installing new version 0.2.1 at CI

### ISSUE THREAD

**Issue by DmytroLitvinov** [shinneider/django-admin-inline-paginator#12]
We @shinneider ,
We have upgraded the package  to `0.2.1` and it started to fail at our GitLab CI.

Here is a traceback of it:

```
Collecting django==2.2.24
  Downloading Django-2.2.24-py3-none-any.whl (7.5 MB)
Collecting django-absolute==0.3
  Downloading django-absolute-0.3.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting django-admin-inline-paginator==0.2.1
  Downloading django-admin-inline-paginator-0.2.1.tar.gz (7.5 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/gitlab-runner/builds/hi3SfEg7/0/NephilaAG/gryps-project/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nm11c9y_/django-admin-inline-paginator_efb36415eafa45c2880fee38d38dbf5f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nm11c9y_/django-admin-inline-paginator_efb36415eafa45c2880fee38d38dbf5f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cfrtmicm
       cwd: /tmp/pip-install-nm11c9y_/django-admin-inline-paginator_efb36415eafa45c2880fee38d38dbf5f/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-nm11c9y_/django-admin-inline-paginator_efb36415eafa45c2880fee38d38dbf5f/setup.py", line 7, in <module>
      from django_admin_inline_paginator.meta import VERSION
    File "/tmp/pip-install-nm11c9y_/django-admin-inline-paginator_efb36415eafa45c2880fee38d38dbf5f/django_admin_inline_paginator/__init__.py", line 2, in <module>
      from django import __version__ as django_version
  ModuleNotFoundError: No module named 'django'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bb/fe/6e014aa386cdfebbdd140ceccd4d3df50d8d8141fb546b3bfb47efcfeeb3/django-admin-inline-paginator-0.2.1.tar.gz#sha256=f0af26ef6ea8ae74084fe5c3dc44f942a15efbb9d49ce1fee260f566ff3ccb6a (from https://pypi.org/simple/django-admin-inline-paginator/) (requires-python:>=3.3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement django-admin-inline-paginator==0.2.1 (from versions: 0.1, 0.1.1, 0.2, 0.2.1)
ERROR: No matching distribution found for django-admin-inline-paginator==0.2.1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1
```

The affected commit: https://github.com/shinneider/django-admin-inline-paginator/commit/528272b7ab184c16834feb4a169b464fbff47623

Still not sure is it a problem at CI or at configuration for `setup.py` file.

**Comment by DmytroLitvinov** [comment]
Here is a workaround at [django-channels](https://github.com/django/channels/commit/d58fa915665c3a2c99588bb19bfaf14e6728371f).

**Comment by compagnt** [comment]
Another temporary option is to install this post your standard requirements.txt, that worked for me. Not ideal but got my CI running.

**Comment by DmytroLitvinov** [comment]
Hi @compagnt ,
I did get what do you mean under the phrase "install this post your standard requirements.txt"?

**Comment by compagnt** [comment]
Hi @DmytroLitvinov ,

Sorry what I meant was to run your main pip install -r requirements.txt that contains django, then after that run a pip-install -r requirements2.txt that contains just this package reference.

**Comment by DmytroLitvinov** [comment]
Hi @shinneider ,
Any chance on merging and releasing it at PyPI?

**Comment by DmytroLitvinov** [comment]
Thanks for releasing at PyPI new version @shinneider :)

**Comment by shinneider** [comment]
@DmytroLitvinov Yes.
i released a version 0.2.2 with this fix.

and i keep this PR for more days, Because i tested locally only...
if you have problem in production, tell me here

**Comment by shinneider** [comment]
Guys sorry for long time to response, however this last year i no have much time :( , home moving, new job, new country, coronavirus problems... anyway...

**Comment by DmytroLitvinov** [comment]
@shinneider , tested at my project. Everything is working as expected :tada: 

Hope everything is okay in your life now :pray:
